config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :users
  resources :tasks do
    member do
      post :add_child
    end
    put :assign_user, on: :member
  end
  resources :projects
  resources :papers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"

  # get "/tasks", to: "tasks#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user, optional: true
  belongs_to :parent, class_name: 'Task', optional: true
  has_many :children, class_name: 'Task', foreign_key: 'parent_id'
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy assign_user add_child]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def assign_user
    @user = User.find(params[:user_id])
    @task.user = @user
    if @task.save
      redirect_to @task, notice: 'User was successfully assigned.'
    else
      redirect_to @task, alert: 'There was an error assigning the user.'
    end
  end

  def add_child
    child_task = @task.children.new(task_params)
    child_task.project = @task.project
    if child_task.save
      render json: { status: 'success', message: 'Child task was successfully added.' }
    else
      render json: { status: 'error', message: 'There was a problem adding the child task.', errors: child_task.errors }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :description, :project_id, :user_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.collection_select :project_id, Project.all, :id, :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= task.project_id %>
  </p>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <% if @task.user.nil? %>
    <%= form_with url: assign_user_task_path(@task), method: :put do %>
      <%= select_tag :user_id, options_from_collection_for_select(User.all, :id, :name) %>
      <%= submit_tag "Assign user to this task" %>
    <% end %>
  <% else %>
    User assigned: <%= @task.user.name %>
  <% end %>
</div>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %> |
  <%= button_to "Destroy this task", @task, method: :delete %>
</div>

<h2>Add Child Task</h2>
<%= form_for @task.children.new, url: add_child_task_path(@task), method: :post do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit "Add Child Task" %>
  </div>
<% end %>

<% if @task.children.exists? %>
  <h2>Child Tasks</h2>
  <% @task.children.each do |child_task| %>
    <p>
      <strong>Name:</strong>
      <%= child_task.name %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= child_task.description %>
    </p>
  <% end %>
<% end %>