config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :users
  resources :tasks do
    member do
      post :add_child
    end
    put :assign_user, on: :member
  end
  resources :projects
  resources :papers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"

  # get "/tasks", to: "tasks#index"
end

app/models/paper.rb
class Paper < ApplicationRecord
  has_many :projects
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: %i[ show edit update destroy ]

  # GET /papers or /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers/1 or /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers or /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to paper_url(@paper), notice: "Paper was successfully created." }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1 or /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to paper_url(@paper), notice: "Paper was successfully updated." }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1 or /papers/1.json
  def destroy
    @paper.destroy!

    respond_to do |format|
      format.html { redirect_to papers_url, notice: "Paper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paper_params
      params.require(:paper).permit(:name, :description)
    end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= form_with(model: paper) do |form| %>
  <% if paper.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
        <% paper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/papers/_paper.html.erb
<div id="<%= dom_id paper %>">
  <p>
    <strong>Name:</strong>
    <%= paper.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= paper.description %>
  </p>

</div>

app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render "form", paper: @paper %>

<br>

<div>
  <%= link_to "Show this paper", @paper %> |
  <%= link_to "Back to papers", papers_path %>
</div>

app/views/papers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Papers</h1>

<div id="papers">
  <% @papers.each do |paper| %>
    <%= render paper %>
    <p>
      <%= link_to "Show this paper", paper %>
      <% paper.projects.each do |project| %>
        <p>
          <%= link_to "Go to #{project.name}", project %>
        </p>
      <% end %>
    </p>
  <% end %>
</div>

<%= link_to "New paper", new_paper_path %>

app/views/papers/new.html.erb
<h1>New paper</h1>

<%= render "form", paper: @paper %>

<br>

<div>
  <%= link_to "Back to papers", papers_path %>
</div>

app/views/papers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @paper %>

<div>
  <%= link_to "Edit this paper", edit_paper_path(@paper) %> |
  <%= link_to "Back to papers", papers_path %>

  <%= button_to "Destroy this paper", @paper, method: :delete %>
</div>